### ISSUE TITLE
Could not find version from 'git describe --tags' or from video_splitter.egg-info/version_full.txt

### ISSUE THREAD

**Issue by ruuter** [krichter722/video-splitter#1]
Running `pip install git+git://github.com/krichter722/video-splitter.git` resulted in following output:

```
------------------------------------------------------------
/usr/bin/pip run on Sun Oct  9 01:40:20 2016
Downloading/unpacking git+git://github.com/krichter722/video-splitter.git
  Cloning git://github.com/krichter722/video-splitter.git to /tmp/pip-22ctJz-build
  Found command 'git' at '/usr/bin/git'
  Running command /usr/bin/git clone -q git://github.com/krichter722/video-splitter.git /tmp/pip-22ctJz-build
  Running setup.py (path:/tmp/pip-22ctJz-build/setup.py) egg_info for package from git+git://github.com/krichter722/video-splitter.git
    zip_safe flag not set; analyzing archive contents...

    Installed /tmp/pip-22ctJz-build/.eggs/setuptools_version_command-2.2-py2.7.egg
    fatal: No names found, cannot describe anything.
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-22ctJz-build/setup.py", line 65, in <module>
        keywords = "video-edition, automation, video-scene-split",
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 318, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 376, in finalize_options
        ep.load()(self, ep.name, value)
      File "build/bdist.linux-x86_64/egg/setuptools_version_command.py", line 30, in validate_version_command_keyword
    Exception: Could not find version from 'git describe --tags' or from video_splitter.egg-info/version_full.txt
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...



Installed /tmp/pip-22ctJz-build/.eggs/setuptools_version_command-2.2-py2.7.egg

fatal: No names found, cannot describe anything.

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-22ctJz-build/setup.py", line 65, in <module>

    keywords = "video-edition, automation, video-scene-split",

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 318, in __init__

    _Distribution.__init__(self, attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 376, in finalize_options

    ep.load()(self, ep.name, value)

  File "build/bdist.linux-x86_64/egg/setuptools_version_command.py", line 30, in validate_version_command_keyword

Exception: Could not find version from 'git describe --tags' or from video_splitter.egg-info/version_full.txt

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-22ctJz-build
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-22ctJz-build

```

**Comment by krichter722** [comment]
This should be fixed after pushing the tags, now. Thanks for the report.
